package:
  name: mpl-probscale
  version: 0.1.2

source:
  fn: mpl-probscale-0.1.2.tar.gz
  url: https://github.com/phobson/mpl-probscale/archive/v0.1.2.tar.gz
  sha256: 92b7eac1f3a2e9ef5796cd2a8e5bb786b4c2511e1ccd3d6017aa0f33b839996d


build:
  number: 0
  script: pip install . --no-deps

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - nose

test:
  imports:
    - probscale
    
  requires:
    - nose
    - scipy

  commands:
    - python -c "import matplotlib; matplotlib.use('agg'); import probscale; probscale.test()"

about:
  home: http://phobson.github.io/mpl-probscale/
  license:  BSD 3-clause
  summary: 'Probability scales for matplotlib.'

extra:
    recipe-maintainers:
        - phobson
