travis:
  secure:
    BINSTAR_TOKEN: G4ANDU7qB48fjXOuhuxko7MEkR3hDQ/6Ync96O/LmiIzdKlZlJ+UN3jY5ip9d3T/VCs+KURBT4o1aeOj7UxKeORLtjw8fxxzLhddsdo1hQZ61RouSBEW3cWVD5JmQ45DKjkmQ41Zpuuo2wvglR9x54ltQ5COpNtP0WVfmF3bcHYR02gLw4n1gKLmzGP9tYbZzQxZCAvq9/XOy5hmuxMFF9tU+o+vI7ogQyx7Njf4Ptn+QoJL3tXtcNx8D6serX7hWs9KX/hqzJ7CUXbJ9W4iV4xwlObHSAhMBzbzxkMphHMLCiQGjQkXwlpV4X1UfGvBtdcczACPLRcmI8M+5YbA/5kAH14TgCFt5EcUYzuyg5lnnzJVSMoLPhdvmhDxbRwp3FGF/P0lxIqiQMLxmOY/2uvdY3E6Y9WWM7D8sVBF8apF314Oc919T1LH9cZuUdqfon4EEEqHOMODfhL28ytcepPGdzb3nEoLKkqxsVvvGe81pl6rgRcGb2kElX9yL29zuxBEzqN1wPSZjj4EBsBHAtbMXHOmex+k1o5YqV3sbqsvFfxb/Q17JSuw57YcpsF25ZVUFCXUeh7qMwp8lIZpA1uBlEDUDD1UHRg/5+6WpqYQvpiBG+29/LTOZkfkDItKwTrL+tryvuId/5GhElRivt91ip7eYkiW3Nee1GWh7rg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
